q=int(input("enter the prime number q:"))
a=int(input("enter the primitve root a:"))
Xa=int(input("enter the private key of A:"))
Xb=int(input("enter the private key of B:"))
Ya=pow(a,Xa,q)
Yb=pow(a,Xb,q)
print("public key of A is:",Ya)
print("public key of B is:",Yb)
Ka=pow(Yb,Xa,q)
Kb=pow(Ya,Xb,q)
print("Secret key of A is:",Ka)
print("Secret key of B is:",Kb)